name: native_camera_controller_platform_interface
description: A common platform interface for the native_camera_controller plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.6.1
  very_good_analysis: ^6.0.0
