name: native_camera_controller_android_example
description: "Demonstrates how to use the native_camera_controller_android plugin."
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  native_camera_controller_android:
    path: ../../packages/native_camera_controller_android
  native_camera_controller_platform_interface:
    path: ../../packages/native_camera_controller_platform_interface
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
