name: native_camera_controller_android
description: Android implementation of the native_camera_controller plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: native_camera_controller
    platforms:
      android:
        package: com.flashandroid.camera
        pluginClass: NativeCameraControllerPlugin
        dartPluginClass: NativeCameraControllerAndroid

dependencies:
  flutter:
    sdk: flutter
  native_camera_controller_platform_interface:
    path: ../native_camera_controller_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
