name: Melos CI

on:
  pull_request:
    branches:
      - main

jobs:
  melos-checks:
    name: Run Melos CI
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ¯ Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: ğŸ“¦ Install Melos
        run: dart pub global activate melos

      - name: ğŸš€ Bootstrap Melos
        run: melos bootstrap

      - name: ğŸ” Analyze Code
        run: melos run analyze

      - name: ğŸ§¹ Format Code
        run: melos run format

      - name: ğŸ›  Build Generated Files
        run: melos run build

      - name: ğŸš€ Upgrade Dependencies
        run: melos run upgrade